// src/app/privacy-policy/page.tsx
// Maa Flavours — Privacy Policy Page
// Compliant with Indian IT Act 2000 / IT Rules 2011

import type { Metadata } from "next";
import Link from "next/link";
import { Shield } from "lucide-react";
import StaticPageLayout, { OrnamentLine } from "@/components/layout/StaticPageLayout";

export const metadata: Metadata = {
  title: "Privacy Policy — Maa Flavours",
  description: "How Maa Flavours collects, uses, and protects your personal data. We take your privacy seriously.",
};

function PolicySection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-10">
      <h2 className="font-playfair font-bold text-xl sm:text-2xl mb-4" style={{ color: "var(--color-brown)" }}>{title}</h2>
      <OrnamentLine className="w-14 mb-5" />
      <div className="font-dm-sans text-sm sm:text-base leading-relaxed space-y-3" style={{ color: "var(--color-grey)" }}>
        {children}
      </div>
    </div>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <ul className="flex flex-col gap-2 mt-2">
      {items.map((item) => (
        <li key={item} className="flex items-start gap-2.5">
          <span className="w-1.5 h-1.5 rounded-full flex-shrink-0 mt-2" style={{ background: "var(--color-gold)" }} />
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
}

export default function PrivacyPolicyPage() {
  return (
    <StaticPageLayout
      title="Privacy Policy"
      subtitle="How we collect, use, and protect your information"
      emoji="🔒"
      breadcrumb="Privacy Policy"
      updatedAt="Last updated: July 2025"
    >
      {/* Intro */}
      <div className="flex gap-4 p-5 rounded-2xl mb-10"
        style={{ background: "rgba(200,150,12,0.05)", border: "1px solid rgba(200,150,12,0.15)" }}>
        <Shield size={20} style={{ color: "var(--color-gold)", flexShrink: 0, marginTop: "2px" }} />
        <div>
          <p className="font-dm-sans font-bold text-sm" style={{ color: "var(--color-brown)" }}>Our Privacy Commitment</p>
          <p className="font-dm-sans text-sm mt-1 leading-relaxed" style={{ color: "var(--color-grey)" }}>
            Maa Flavours ("we", "us", "our") is committed to protecting your personal information and your right to privacy. This policy describes what information we collect, how we use it, and your rights over it. If you have any questions, contact us at <a href="mailto:maaflavours74@gmail.com" className="underline" style={{ color: "var(--color-crimson)" }}>maaflavours74@gmail.com</a>.
          </p>
        </div>
      </div>

      <OrnamentLine className="mb-8" />

      <PolicySection title="1. Information We Collect">
        <p>We collect information you provide directly to us and information generated by your use of our website:</p>
        <p><strong style={{ color: "var(--color-brown)" }}>Information you provide:</strong></p>
        <BulletList items={[
          "Mobile number (for OTP-based login and order communication)",
          "Name (provided during account creation or checkout)",
          "Email address (optional — provided for newsletters or order confirmation)",
          "Delivery addresses (saved for faster checkout)",
          "Order history and preferences",
          "Messages and queries sent through our contact form",
        ]} />
        <p className="mt-3"><strong style={{ color: "var(--color-brown)" }}>Information collected automatically:</strong></p>
        <BulletList items={[
          "Device information (browser type, operating system)",
          "IP address and approximate location (city level)",
          "Pages visited and time spent on our website",
          "Referral source (how you found us)",
          "Cart interactions and product views",
        ]} />
      </PolicySection>

      <PolicySection title="2. How We Use Your Information">
        <p>We use the information we collect for the following purposes:</p>
        <BulletList items={[
          "Processing and delivering your orders",
          "Sending order confirmations and delivery updates via SMS",
          "Verifying your identity during OTP login",
          "Responding to your queries and support requests",
          "Sending promotional offers and newsletter (only if you opted in — unsubscribe anytime)",
          "Improving our website, products, and services",
          "Detecting and preventing fraud or unauthorised access",
          "Complying with legal obligations under Indian law",
        ]} />
        <p>We will never sell, rent, or trade your personal information to any third party for their marketing purposes.</p>
      </PolicySection>

      <PolicySection title="3. Information Sharing">
        <p>We share your information only in the following limited circumstances:</p>
        <div className="flex flex-col gap-3 mt-3">
          {[
            { title: "Delivery Partners", desc: "We share your name, address, and mobile number with our courier partners (DTDC, BlueDart, India Post) solely for the purpose of delivering your order." },
            { title: "Payment Processors", desc: "Payments are processed by Razorpay. We do not store your card or bank details. Razorpay's privacy policy governs how they handle your payment information." },
            { title: "SMS / OTP Service", desc: "We use Twilio to send OTP messages and delivery notifications. Your mobile number is shared with Twilio for this purpose." },
            { title: "Legal Requirements", desc: "We may disclose information if required by law, court order, or to protect the rights and safety of our users or business." },
          ].map((item) => (
            <div key={item.title} className="p-4 rounded-xl" style={{ background: "var(--color-cream)", border: "1px solid rgba(200,150,12,0.12)" }}>
              <p className="font-dm-sans font-bold text-sm" style={{ color: "var(--color-brown)" }}>{item.title}</p>
              <p className="font-dm-sans text-sm mt-1 leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </PolicySection>

      <PolicySection title="4. Data Storage and Security">
        <p>Your data is stored securely using Supabase (hosted on AWS infrastructure) with industry-standard encryption. All data transfers between your browser and our servers are encrypted using SSL/TLS.</p>
        <p>We implement the following security measures:</p>
        <BulletList items={[
          "OTP authentication (no passwords stored)",
          "JWT tokens stored in httpOnly cookies (not accessible to JavaScript)",
          "Database access restricted to authorised services only",
          "Regular security reviews and updates",
        ]} />
        <p>While we take all reasonable measures to protect your data, no method of internet transmission or electronic storage is 100% secure. We will notify you if a security breach affects your data.</p>
      </PolicySection>

      <PolicySection title="5. Cookies">
        <p>We use the following types of cookies on our website:</p>
        <BulletList items={[
          "Essential cookies: Required for login sessions and cart functionality — cannot be disabled",
          "Analytics cookies: Help us understand how visitors use our site (can be disabled in browser settings)",
          "No advertising/tracking cookies — we do not run targeted ad campaigns through third-party cookies",
        ]} />
        <p>You can control cookie settings through your browser preferences. Disabling essential cookies may affect your ability to use the website fully.</p>
      </PolicySection>

      <PolicySection title="6. Your Rights">
        <p>You have the following rights regarding your personal information:</p>
        <BulletList items={[
          "Right to access: Request a copy of the personal data we hold about you",
          "Right to correction: Ask us to correct any inaccurate information",
          "Right to deletion: Request deletion of your account and associated data",
          "Right to opt-out: Unsubscribe from marketing communications at any time",
          "Right to data portability: Request your data in a machine-readable format",
        ]} />
        <p>To exercise any of these rights, contact us at <a href="mailto:maaflavours74@gmail.com" className="underline" style={{ color: "var(--color-crimson)" }}>maaflavours74@gmail.com</a> with the subject line "Privacy Request". We will respond within 7 working days.</p>
      </PolicySection>

      <PolicySection title="7. Data Retention">
        <p>We retain your personal data for as long as your account is active, and for the following periods after account closure:</p>
        <BulletList items={[
          "Order records: 7 years (required by Indian tax regulations)",
          "Contact form messages: 1 year",
          "Analytics data: 2 years (anonymised)",
          "Marketing consent records: Until withdrawn + 1 year",
        ]} />
      </PolicySection>

      <PolicySection title="8. Children's Privacy">
        <p>Our website is not directed at children under the age of 18. We do not knowingly collect personal information from minors. If we learn that we have collected information from a child, we will delete it promptly. If you believe we have information about a child, please contact us.</p>
      </PolicySection>

      <PolicySection title="9. Changes to This Policy">
        <p>We may update this Privacy Policy from time to time. When we do, we will update the "Last updated" date at the top of this page and notify registered users via SMS or email for significant changes. We encourage you to review this policy periodically.</p>
      </PolicySection>

      <PolicySection title="10. Contact Us">
        <p>For any privacy-related queries, requests, or concerns, reach out to:</p>
        <div className="p-4 rounded-2xl mt-3" style={{ background: "var(--color-cream)", border: "1px solid rgba(200,150,12,0.12)" }}>
          <p className="font-dm-sans font-bold text-sm" style={{ color: "var(--color-brown)" }}>Maa Flavours — Privacy Officer</p>
          <p className="font-dm-sans text-sm mt-1" style={{ color: "var(--color-grey)" }}>
            📧 <a href="mailto:maaflavours74@gmail.com" className="underline" style={{ color: "var(--color-crimson)" }}>maaflavours74@gmail.com</a><br />
            📍 Ongole, Andhra Pradesh, India — 523001<br />
            ⏱️ Response time: Within 7 working days
          </p>
        </div>
      </PolicySection>
    </StaticPageLayout>
  );
}
